version: '2'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_service_db

    ports:
      - 5432:5432
    networks:
      - application-network

  dbeaver:
     image: dbeaver/cloudbeaver:latest
     restart: always
     ports:
      - 8978:8978
     networks:
       - application-network

  user-service:
    image: alaeldinmusa/user-service:latest
    container_name: user-container
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: user_service_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - application-network
    depends_on:
      - postgres
networks:
  application-network:
    driver: bridge
